from pydantic import BaseModel , Field
from langchain_core.output_parsers import PydanticOutputParser

class LLM_Response(BaseModel):

    response : str = Field(description='Response generated by the LLM')


llm_parser=PydanticOutputParser(pydantic_object=LLM_Response)